language: ruby
rvm:
  - 2.1.2
env:
  - DB=mysql
script:
  - RAILS_ENV=test bundle exec rake db:create db:structure:load --trace
  - bundle exec rake
before_script:
  - mysql -e 'create database saudecontrolada_test;'

